name: daily_report

on:
  # 8:00 UTC -> 16:00 Beijing
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  daily-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout farm-bot
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 1
          persist-credentials: true

      - name: Checkout quant-tracer
        uses: actions/checkout@v4
        with:
          repository: w3ntao/quant-tracer
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: quant-tracer
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Prepare repository
        run: |
          bash quant-tracer/configure.sh

      - name: daily report
        working-directory: quant-tracer
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python quant_tracer.py --daily_report
