name: daily_update

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout farm-bot
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 1
          persist-credentials: true

      - name: Checkout quant-tracer
        uses: actions/checkout@v4
        with:
          repository: w3ntao/quant-tracer
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: quant-tracer
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true

      - name: Checkout farm
        uses: actions/checkout@v4
        with:
          repository: w3ntao/farm
          token: ${{ secrets.KEY_QUANT_TRACER_RECUR }}
          path: farm
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Prepare repository
        run: |
          bash quant-tracer/configure.sh

      - name: update
        working-directory: quant-tracer
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          python cron_worker.py --daily_update
